name: Add Size Label to PR
# This workflow is triggered on pushes to the repository.
on:
  pull_request

jobs:
  build:
    # Job name is Greeting
    name: Add Size Label to PR
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Add Size Label to PR
        uses: WizardOhio24/label-pr-size-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
